pipeline {
    agent any

    triggers {
        githubPush()
    }

    stages {
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Build and Deploy Project') {
            steps {
                script {
                    dir('/workspace') {
                        sh 'docker-compose up --build -d'
                    }
                }
            }
        }
    }

    post {
        always {
            script {
                dir('/workspace') {
                    sh 'docker-compose down'
                }
                // Limpiar imágenes no utilizadas
                sh 'docker system prune -f'
            }
        }
    }
}